# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CiThief < Formula
  desc "Simple CLI tool to fetch GitLab CI variables and output them as exportable environment variables."
  homepage "https://containeroo.ch"
  version "2.3.1"
  license "GNU General Public License v3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/containeroo/ci-thief/releases/download/v2.3.1/ci-thief_2.3.1_darwin_amd64.tar.gz"
      sha256 "1c442d31a54ef930e7232c9dec8aa2fd30ac65efa30ac2de273b1eb94af917b8"

      def install
        bin.install "ci-thief"

        # Install bash completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "bash")
        (bash_completion/"ci-thief").write output

        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "zsh")
        (zsh_completion/"_ci-thief").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/containeroo/ci-thief/releases/download/v2.3.1/ci-thief_2.3.1_darwin_arm64.tar.gz"
      sha256 "460d0a3a62e4114f11fe0b57b1e480e27b0cf1a19144f878aa300155ca74b145"

      def install
        bin.install "ci-thief"

        # Install bash completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "bash")
        (bash_completion/"ci-thief").write output

        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "zsh")
        (zsh_completion/"_ci-thief").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/containeroo/ci-thief/releases/download/v2.3.1/ci-thief_2.3.1_linux_amd64.tar.gz"
      sha256 "5ac7cb51abb26cee892f0b938f8ba39948097e34792d26ad68fd50f5db4a3ef0"
      def install
        bin.install "ci-thief"

        # Install bash completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "bash")
        (bash_completion/"ci-thief").write output

        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "zsh")
        (zsh_completion/"_ci-thief").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/containeroo/ci-thief/releases/download/v2.3.1/ci-thief_2.3.1_linux_arm64.tar.gz"
      sha256 "b1e4a24bb9d8284374c365f5dfd56489e5bbe88bad498afd88bef14c1ee95ece"
      def install
        bin.install "ci-thief"

        # Install bash completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "bash")
        (bash_completion/"ci-thief").write output

        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "zsh")
        (zsh_completion/"_ci-thief").write output
      end
    end
  end
end
