# This file was generated by GoReleaser. DO NOT EDIT.
cask "certinfo" do
  name "certinfo"
  desc "Get information about the certificate from one or more hostnames"
  homepage "https://containeroo.ch"
  version "1.4.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certinfo"

  on_macos do
    on_intel do
      url "https://github.com/containeroo/certinfo/releases/download/v#{version}/certinfo_#{version}_darwin_amd64.tar.gz"
      sha256 "8039531be455b4dd5d4c3bf031a72c1bc07866980a0b15535ffedd3253492f5d"
    end
    on_arm do
      url "https://github.com/containeroo/certinfo/releases/download/v#{version}/certinfo_#{version}_darwin_arm64.tar.gz"
      sha256 "76e7597def25bf61e70d648a2557aa009107751208964112fca607678dece1f1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/containeroo/certinfo/releases/download/v#{version}/certinfo_#{version}_linux_amd64.tar.gz"
      sha256 "4f29472c78492c2d7e7cf8dc4f86e0b109ac45b5ada83fe26b53a459db914df3"
    end
    on_arm do
      url "https://github.com/containeroo/certinfo/releases/download/v#{version}/certinfo_#{version}_linux_arm64.tar.gz"
      sha256 "50c33d1575ffd6109958896171484426087b137bc83b7b0f4b3c671610004098"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/certinfo"]
    end
  end

  # No zap stanza required
end
