# This file was generated by GoReleaser. DO NOT EDIT.
cask "certinfo" do
  version "1.4.6"

  on_macos do
    on_intel do
      sha256 "2989439fd3825e49080c8a9723a0676231d122dfa978cc633a59dac83c97f232"
      url "https://github.com/containeroo/certinfo/releases/download/v#{version}/certinfo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "79e3fba3a1dc23d05c9d980ccb674fdf6ed46f95d2257a1c967a30459deedd46"
      url "https://github.com/containeroo/certinfo/releases/download/v#{version}/certinfo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "030f7db8e7253113df5fe2078433c75f81c6aa25f663487370d01f8f22eb4506"
      url "https://github.com/containeroo/certinfo/releases/download/v#{version}/certinfo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a1f10ef7ed23c42ab9f02f23919ca8ed5d027edf749fa5d95c6bbc321473842"
      url "https://github.com/containeroo/certinfo/releases/download/v#{version}/certinfo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "certinfo"
  desc "Get information about the certificate from one or more hostnames"
  homepage "https://containeroo.ch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certinfo"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/certinfo"]
    end
  end

  # No zap stanza required

end
