# This file was generated by GoReleaser. DO NOT EDIT.
cask "certinfo" do
  name "certinfo"
  desc "Get information about the certificate from one or more hostnames"
  homepage "https://containeroo.ch"
  version "1.4.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certinfo"

  on_macos do
    on_intel do
      url "https://github.com/containeroo/certinfo/releases/download/v#{version}/certinfo_#{version}_darwin_amd64.tar.gz"
      sha256 "2925583218aae5440a5fdfbc6bf87bdcb9ef28c92e2074684cb54df92bae806e"
    end
    on_arm do
      url "https://github.com/containeroo/certinfo/releases/download/v#{version}/certinfo_#{version}_darwin_arm64.tar.gz"
      sha256 "d5ccb9f575b476d302d4b3f9cd1aa0cbfcc5ffa19684a43bbbe9aa0dbefea549"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/containeroo/certinfo/releases/download/v#{version}/certinfo_#{version}_linux_amd64.tar.gz"
      sha256 "c1e946129f997e8c0926bb7c5fab26c0bb683072233b687a74323a4f654993a9"
    end
    on_arm do
      url "https://github.com/containeroo/certinfo/releases/download/v#{version}/certinfo_#{version}_linux_arm64.tar.gz"
      sha256 "9838668eab58737d6a42b51dd30a9c7e0cae1b47b76c9f2d732324f397aadd84"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/certinfo"]
    end
  end

  # No zap stanza required
end
