# This file was generated by GoReleaser. DO NOT EDIT.
cask "cfop-generator" do
  name "cfop-generator"
  desc "CLI tool to convert exported Cloudflare zones to cloudflare-operator DNSRecord objects"
  homepage "https://containeroo.ch"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cfop-generator"
  bash_completion "completions/cfop-generator.bash"
  zsh_completion "completions/cfop-generator.zsh"

  on_macos do
    on_intel do
      url "https://github.com/containeroo/cfop-generator/releases/download/v#{version}/cfop-generator_#{version}_darwin_amd64.tar.gz"
      sha256 "621da8ec7bfaa820a8f70fef5fac69025f9cfc8224222689fdb4589c773d8501"
    end
    on_arm do
      url "https://github.com/containeroo/cfop-generator/releases/download/v#{version}/cfop-generator_#{version}_darwin_arm64.tar.gz"
      sha256 "080b23112ec9f265a65b409d5917759b7bbe29bd2ef99287b3c354c1f0b86f80"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/containeroo/cfop-generator/releases/download/v#{version}/cfop-generator_#{version}_linux_amd64.tar.gz"
      sha256 "65b3455f806c0aaf9222444d2647eb314e08dfadf1e30a882a92fcdb5175c490"
    end
    on_arm do
      url "https://github.com/containeroo/cfop-generator/releases/download/v#{version}/cfop-generator_#{version}_linux_arm64.tar.gz"
      sha256 "f48d34e29689c69530070dd4c66c4214b436d79a1aeb5932f9e98520d4d72a87"
    end
  end

  # No zap stanza required
end
