# This file was generated by GoReleaser. DO NOT EDIT.
cask "ci-thief" do
  desc "Simple CLI tool to fetch GitLab CI variables and output them as exportable environment variables."
  homepage "https://containeroo.ch"
  version "2.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ci-thief"

  on_macos do
    on_intel do
      url "https://github.com/containeroo/ci-thief/releases/download/v2.2.0/ci-thief_2.2.0_darwin_amd64.tar.gz"
      sha256 "92f62d392b64c7af92c95ba0037018fc0066dce7c54e876b99edd02a768bd9d1"
    end
    on_arm do
      url "https://github.com/containeroo/ci-thief/releases/download/v2.2.0/ci-thief_2.2.0_darwin_arm64.tar.gz"
      sha256 "06988e92fc809d44e317e1c9b356669740608731b8a04c84b53d5e379e2155de"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/containeroo/ci-thief/releases/download/v2.2.0/ci-thief_2.2.0_linux_amd64.tar.gz"
      sha256 "f01027be9571c1cfa35db878f04715ed1b9277d08304815273df10b2f8d9c8f4"
    end
    on_arm do
      url "https://github.com/containeroo/ci-thief/releases/download/v2.2.0/ci-thief_2.2.0_linux_arm64.tar.gz"
      sha256 "7abb0871a00294c878b02303d7fc077817201fb61e0c9f544430240f88ee6486"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ci-thief"]
    end
  end

  # No zap stanza required
end
