# This file was generated by GoReleaser. DO NOT EDIT.
cask "ci-thief" do
  name "ci-thief"
  desc "Simple CLI tool to fetch GitLab CI variables and output them as exportable environment variables."
  homepage "https://containeroo.ch"
  version "2.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ci-thief"

  on_macos do
    on_intel do
      url "https://github.com/containeroo/ci-thief/releases/download/v#{version}/ci-thief_#{version}_darwin_amd64.tar.gz"
      sha256 "39198f33552456694a26cef03daded345eaf8cbe1c2fb34b4f77447356ac2065"
    end
    on_arm do
      url "https://github.com/containeroo/ci-thief/releases/download/v#{version}/ci-thief_#{version}_darwin_arm64.tar.gz"
      sha256 "8260037dbfe407d62b8b862a205cfd5b4f55a1e0fef31d9309cf00699b73fbe0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/containeroo/ci-thief/releases/download/v#{version}/ci-thief_#{version}_linux_amd64.tar.gz"
      sha256 "afb4c1ef9db5172c7bdbe6e7a40da2005c41332e3c9ff3015759c0c6c9087b7b"
    end
    on_arm do
      url "https://github.com/containeroo/ci-thief/releases/download/v#{version}/ci-thief_#{version}_linux_arm64.tar.gz"
      sha256 "c423ecd86168bf25dfa6b81931af899fd4e0ba08d13bc40e7a28a49f0ca62d37"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ci-thief"]
    end
  end

  # No zap stanza required
end
