# This file was generated by GoReleaser. DO NOT EDIT.
cask "dologen" do
  name "dologen"
  desc "Simple CLI tool to generate Docker config.json with registry credentials"
  homepage "https://containeroo.ch"
  version "1.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dologen"
  bash_completion "completions/dologen.bash"
  zsh_completion "completions/dologen.zsh"

  on_macos do
    on_intel do
      url "https://github.com/containeroo/dologen/releases/download/v#{version}/dologen_#{version}_darwin_amd64.tar.gz"
      sha256 "a1520734d21a367ecf1de2e138a06eba1e4f9d3fe33ff4c49b30c3b0af2359b6"
    end
    on_arm do
      url "https://github.com/containeroo/dologen/releases/download/v#{version}/dologen_#{version}_darwin_arm64.tar.gz"
      sha256 "94304a3fdaf0fd967a503c3ad84c42789643df62ecf9d9b18e279cbb50961104"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/containeroo/dologen/releases/download/v#{version}/dologen_#{version}_linux_amd64.tar.gz"
      sha256 "45fa5a49fa8927990c79f7142e9b727f3026f3dd1bcac509fd6cb1ad9b1e12a2"
    end
    on_arm do
      url "https://github.com/containeroo/dologen/releases/download/v#{version}/dologen_#{version}_linux_arm64.tar.gz"
      sha256 "91e15000490b4930711bc77179709925e1440ce86b6f2b616ec7d7a0ef79f488"
    end
  end

  postflight do
    if OS.mac?
      system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/dologen"
    end
  end

  # No zap stanza required
end
