# This file was generated by GoReleaser. DO NOT EDIT.
cask "dologen" do
  name "dologen"
  desc "Simple CLI tool to generate Docker config.json with registry credentials"
  homepage "https://containeroo.ch"
  version "1.2.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dologen"
  bash_completion "completions/dologen.bash"
  zsh_completion "completions/dologen.zsh"

  on_macos do
    on_intel do
      url "https://github.com/containeroo/dologen/releases/download/v#{version}/dologen_#{version}_darwin_amd64.tar.gz"
      sha256 "8f05d4e50a8645a3d239e6c5e8e9efb0343928f985fb6e6a5705873fbf1b7350"
    end
    on_arm do
      url "https://github.com/containeroo/dologen/releases/download/v#{version}/dologen_#{version}_darwin_arm64.tar.gz"
      sha256 "0be74d1bcf79a74e1c1ef32523273826d3b5f59589dd37d62a1b41e431951ad1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/containeroo/dologen/releases/download/v#{version}/dologen_#{version}_linux_amd64.tar.gz"
      sha256 "f7a88c8dd9145321b1f5adbcc35dba64e8abe4edabb4545190f1ec460a3f3cd6"
    end
    on_arm do
      url "https://github.com/containeroo/dologen/releases/download/v#{version}/dologen_#{version}_linux_arm64.tar.gz"
      sha256 "632922639ac91d521c848281fde73559fde6cec7f509893b5a688943417794fb"
    end
  end

  postflight do
    if OS.mac?
      system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/dologen"
    end
  end

  # No zap stanza required
end
