# This file was generated by GoReleaser. DO NOT EDIT.
cask "dologen" do
  name "dologen"
  desc "Simple CLI tool to generate Docker config.json with registry credentials"
  homepage "https://containeroo.ch"
  version "1.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dologen"
  bash_completion "completions/dologen.bash"
  zsh_completion "completions/dologen.zsh"

  on_macos do
    on_intel do
      url "https://github.com/containeroo/dologen/releases/download/v#{version}/dologen_#{version}_darwin_amd64.tar.gz"
      sha256 "150714dddf755275adec4992816c936f2682c0738db0dfe771e48a12f71e5609"
    end
    on_arm do
      url "https://github.com/containeroo/dologen/releases/download/v#{version}/dologen_#{version}_darwin_arm64.tar.gz"
      sha256 "39582415c9a64c7c322eed6d6265aab4c05c0fb3c46fd799025aac8bdf6c23fe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/containeroo/dologen/releases/download/v#{version}/dologen_#{version}_linux_amd64.tar.gz"
      sha256 "652bf1eb324c28795562e09d5a2c66c3cb36756f864f34e7802c010f4f490fec"
    end
    on_arm do
      url "https://github.com/containeroo/dologen/releases/download/v#{version}/dologen_#{version}_linux_arm64.tar.gz"
      sha256 "b3b1930e73cac4cd52f403d6338548847ef8da098176d3c9f79b7fe19ca941b4"
    end
  end

  postflight do
    if OS.mac?
      system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/dologen"
    end
  end

  # No zap stanza required
end
