# This file was generated by GoReleaser. DO NOT EDIT.
cask "otpgen" do
  name "otpgen"
  desc "Simple CLI tool to generate OTP tokens"
  homepage "https://containeroo.ch"
  version "3.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "otpgen"
  bash_completion "completions/otpgen.bash"
  zsh_completion "completions/otpgen.zsh"

  on_macos do
    on_intel do
      url "https://github.com/containeroo/otpgen/releases/download/v#{version}/otpgen_#{version}_darwin_amd64.tar.gz"
      sha256 "3a42c2e71fb973e597e9061321031bd9004653bc019ac0fbf7f9d1204bc99a3f"
    end
    on_arm do
      url "https://github.com/containeroo/otpgen/releases/download/v#{version}/otpgen_#{version}_darwin_arm64.tar.gz"
      sha256 "0ec9011bfc560998ec8d8166a29f144c4e6a61dc2a32596a6c7e2092ebaf18b2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/containeroo/otpgen/releases/download/v#{version}/otpgen_#{version}_linux_amd64.tar.gz"
      sha256 "b4b07db242bfea3aaf696dd580a426f6b77b9e108c683713b4c66737746604ec"
    end
    on_arm do
      url "https://github.com/containeroo/otpgen/releases/download/v#{version}/otpgen_#{version}_linux_arm64.tar.gz"
      sha256 "be12b8183f66273436758828a306dbec7062e5a1922137c6f0bae5f166158a41"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/otpgen"], must_succeed: false
  end

  # No zap stanza required
end
