# This file was generated by GoReleaser. DO NOT EDIT.
cask "otpgen" do
  name "otpgen"
  desc "Simple CLI tool to generate OTP tokens"
  homepage "https://containeroo.ch"
  version "3.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "otpgen"
  bash_completion "completions/otpgen.bash"
  zsh_completion "completions/otpgen.zsh"

  on_macos do
    on_intel do
      url "https://github.com/containeroo/otpgen/releases/download/v#{version}/otpgen_#{version}_darwin_amd64.tar.gz"
      sha256 "a99a7642f1bf8402007b5d0576e9edff3a2add816aced4f702d80bcdfacbe6d4"
    end
    on_arm do
      url "https://github.com/containeroo/otpgen/releases/download/v#{version}/otpgen_#{version}_darwin_arm64.tar.gz"
      sha256 "80182665c0f78bbb3774b6772a323b8037a20b863109fefddea8981a1da8631d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/containeroo/otpgen/releases/download/v#{version}/otpgen_#{version}_linux_amd64.tar.gz"
      sha256 "9ac8ff8e1f3e50e8dc1fdc3e0df49e9a9229ab43c22af12a5f5c5a6f48ed272a"
    end
    on_arm do
      url "https://github.com/containeroo/otpgen/releases/download/v#{version}/otpgen_#{version}_linux_arm64.tar.gz"
      sha256 "4bea9b34ec917556fcb6e64d35181726f08298d3c26d3cad7554346ee551d50a"
    end
  end

  postflight do
    xattr -dr com.apple.quarantine "#{staged_path}/otpgen" || true
  end

  # No zap stanza required
end
