# This file was generated by GoReleaser. DO NOT EDIT.
cask "otpgen" do
  name "otpgen"
  desc "Simple CLI tool to generate OTP tokens"
  homepage "https://containeroo.ch"
  version "3.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "otpgen"
  bash_completion "completions/otpgen.bash"
  zsh_completion "completions/otpgen.zsh"

  on_macos do
    on_intel do
      url "https://github.com/containeroo/otpgen/releases/download/v#{version}/otpgen_#{version}_darwin_amd64.tar.gz"
      sha256 "bdd954da535def2ea4e81b69251651ceac2ad954d7704150f520be949595f7c6"
    end
    on_arm do
      url "https://github.com/containeroo/otpgen/releases/download/v#{version}/otpgen_#{version}_darwin_arm64.tar.gz"
      sha256 "d37a427f71abfd5b47c2c02d096eb000bd955a99a929d327fed034b03d762c93"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/containeroo/otpgen/releases/download/v#{version}/otpgen_#{version}_linux_amd64.tar.gz"
      sha256 "5ac1603e0313d6a5636e1480b171bfda841a1852648fe9151f07f442b2e0bc67"
    end
    on_arm do
      url "https://github.com/containeroo/otpgen/releases/download/v#{version}/otpgen_#{version}_linux_arm64.tar.gz"
      sha256 "53c96f6e6739e3844c6498e444e3f559120e35bb4ea6a4aa222ffa4be0ff870c"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/otpgen"], must_succeed: false
  end

  # No zap stanza required
end
