# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Certinfo < Formula
  desc "Get information about the certificate from one or more hostnames"
  homepage "https://containeroo.ch"
  version "1.3.12"
  license "GNU General Public License v3.0"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/containeroo/certinfo/releases/download/v1.3.12/certinfo_1.3.12_darwin_arm64.tar.gz"
      sha256 "84c577dce4a5f8017b8925d3872511e22778be71f68b256bf67d2254505faacf"

      def install
        bin.install "certinfo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/containeroo/certinfo/releases/download/v1.3.12/certinfo_1.3.12_darwin_amd64.tar.gz"
      sha256 "3b2bd3ea708197d9f01ef7dca8809ab3b6eecb9319390ee916a654786ae47d40"

      def install
        bin.install "certinfo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/containeroo/certinfo/releases/download/v1.3.12/certinfo_1.3.12_linux_amd64.tar.gz"
      sha256 "b8679c4a1b827007c6ecfe5ad54abf85f1ae5c227bbd35a0e98fa4c7d4c6c6c9"

      def install
        bin.install "certinfo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/containeroo/certinfo/releases/download/v1.3.12/certinfo_1.3.12_linux_arm64.tar.gz"
      sha256 "4892f4338350b459564ac4d36adf536f7c2a748f679ac7000660cb66f10db4f5"

      def install
        bin.install "certinfo"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/containeroo/certinfo/releases/download/v1.3.12/certinfo_1.3.12_linux_armv6.tar.gz"
      sha256 "d32b9b28d9f2bf3dd8db095b391977cb178d8ab4b3c2f19b7c5837cbc269ddb1"

      def install
        bin.install "certinfo"
      end
    end
  end

  test do
    system "#{bin}/certinfo --version"
  end
end
