# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CfopGenerator < Formula
  desc "CLI tool to convert exported Cloudflare zones to cloudflare-operator DNSRecord objects"
  homepage "https://containeroo.ch"
  version "0.0.1"
  license "GNU General Public License v3.0"

  depends_on "go" => :optional

  on_macos do
    on_intel do
      url "https://github.com/containeroo/cfop-generator/releases/download/v0.0.1/cfop-generator_0.0.1_darwin_amd64.tar.gz"
      sha256 "55483e038ac2d743b621333f08b7682b1251a44168e360a468b89cd06cbd2d30"

      def install
        bin.install "cfop-generator"
      end
    end
    on_arm do
      url "https://github.com/containeroo/cfop-generator/releases/download/v0.0.1/cfop-generator_0.0.1_darwin_arm64.tar.gz"
      sha256 "71da312dc31aa9d25be451f7a9fe6f18cf029ab378ef1831093eb869198303b7"

      def install
        bin.install "cfop-generator"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/containeroo/cfop-generator/releases/download/v0.0.1/cfop-generator_0.0.1_linux_amd64.tar.gz"
        sha256 "e39827f92fd2fdab4bfc925ad61999fe45c66a42e763ca2c721aa69786faaf71"

        def install
          bin.install "cfop-generator"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/containeroo/cfop-generator/releases/download/v0.0.1/cfop-generator_0.0.1_linux_armv6.tar.gz"
        sha256 "6c82dfd8fa4d5c4843de96933c2dace5562e9fdcb4f03a29fa30c1fb5a859e9b"

        def install
          bin.install "cfop-generator"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/containeroo/cfop-generator/releases/download/v0.0.1/cfop-generator_0.0.1_linux_arm64.tar.gz"
        sha256 "8ad26f130a85ef3f61a2dfb1ac112122f5392a6a69f5a899f044a8f836c4e16d"

        def install
          bin.install "cfop-generator"
        end
      end
    end
  end
end
