# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CfopGenerator < Formula
  desc "CLI tool to convert exported Cloudflare zones to cloudflare-operator DNSRecord objects"
  homepage "https://containeroo.ch"
  version "0.0.3"
  license "GNU General Public License v3.0"

  depends_on "go" => :optional

  on_macos do
    on_intel do
      url "https://github.com/containeroo/cfop-generator/releases/download/v0.0.3/cfop-generator_0.0.3_darwin_amd64.tar.gz"
      sha256 "6c716592d322911406b49eda7a83e71429ce6c37d4fee30559800dbb8609e53a"

      def install
        bin.install "cfop-generator"
      end
    end
    on_arm do
      url "https://github.com/containeroo/cfop-generator/releases/download/v0.0.3/cfop-generator_0.0.3_darwin_arm64.tar.gz"
      sha256 "28f131ab2a25a6d8c5d17c63ddef19349611f5e0a22f494ff9076e10547e60e2"

      def install
        bin.install "cfop-generator"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/containeroo/cfop-generator/releases/download/v0.0.3/cfop-generator_0.0.3_linux_amd64.tar.gz"
        sha256 "e19f6c70626a551edb9a90f0d485840b7d6ea831b6f7afe654b8f420ca328b9f"

        def install
          bin.install "cfop-generator"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/containeroo/cfop-generator/releases/download/v0.0.3/cfop-generator_0.0.3_linux_armv6.tar.gz"
        sha256 "24fd5532ae5eafa9d1fc489269b6e3a58eca7fbf5cc30cd7392fcb1f1407e014"

        def install
          bin.install "cfop-generator"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/containeroo/cfop-generator/releases/download/v0.0.3/cfop-generator_0.0.3_linux_arm64.tar.gz"
        sha256 "27dd708a89633ab092b766d3acf2ebd428e71b7edbbbca59b311c803676b0067"

        def install
          bin.install "cfop-generator"
        end
      end
    end
  end
end
