# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CiThief < Formula
  desc "Simple CLI tool to fetch GitLab CI variables and output them as exportable environment variables."
  homepage "https://containeroo.ch"
  version "2.1.0"
  license "GNU General Public License v3.0"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/containeroo/ci-thief/releases/download/v2.1.0/ci-thief_2.1.0_darwin_arm64.tar.gz"
      sha256 "47d226f0e59c13a61e511bf1cb4f22d865bbc01c92ef019398d29600cdfd90fc"

      def install
        bin.install "ci-thief"

        # Install bash completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "bash")
        (bash_completion/"ci-thief").write output

        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "zsh")
        (zsh_completion/"_ci-thief").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/containeroo/ci-thief/releases/download/v2.1.0/ci-thief_2.1.0_darwin_amd64.tar.gz"
      sha256 "a379cfc438fa9138466108e2f08405b3f565e5b39093332bb60b7f7edca2a9f5"

      def install
        bin.install "ci-thief"

        # Install bash completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "bash")
        (bash_completion/"ci-thief").write output

        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "zsh")
        (zsh_completion/"_ci-thief").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/containeroo/ci-thief/releases/download/v2.1.0/ci-thief_2.1.0_linux_armv6.tar.gz"
      sha256 "bb6afa66959fa354ee582167c19442200e941b721e4fc23c987f0fa9cc650cd3"

      def install
        bin.install "ci-thief"

        # Install bash completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "bash")
        (bash_completion/"ci-thief").write output

        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "zsh")
        (zsh_completion/"_ci-thief").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/containeroo/ci-thief/releases/download/v2.1.0/ci-thief_2.1.0_linux_arm64.tar.gz"
      sha256 "44a900994b2902bee4b27fe007f7990f7efcd5b1b116c0ee52b5c05a3012bb1b"

      def install
        bin.install "ci-thief"

        # Install bash completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "bash")
        (bash_completion/"ci-thief").write output

        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "zsh")
        (zsh_completion/"_ci-thief").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/containeroo/ci-thief/releases/download/v2.1.0/ci-thief_2.1.0_linux_amd64.tar.gz"
      sha256 "a3d2f84ce883bd3bdb5dbfd73c54b3ad0f8917ed42675665b592c7ac51017868"

      def install
        bin.install "ci-thief"

        # Install bash completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "bash")
        (bash_completion/"ci-thief").write output

        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "zsh")
        (zsh_completion/"_ci-thief").write output
      end
    end
  end

  test do
    system "#{bin}/ci-thief version"
  end
end
