# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CiThief < Formula
  desc "Simple CLI tool to fetch GitLab CI variables and output them as exportable environment variables."
  homepage "https://containeroo.ch"
  version "2.0.0"
  license "GNU General Public License v3.0"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/containeroo/ci-thief/releases/download/v2.0.0/ci-thief_2.0.0_darwin_arm64.tar.gz"
      sha256 "6e7705c819a7ebe5c63d7028bd03b93da0001011bad2ea274ad3da18a962d15f"

      def install
        bin.install "ci-thief"

        # Install bash completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "bash")
        (bash_completion/"ci-thief").write output

        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "zsh")
        (zsh_completion/"_ci-thief").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/containeroo/ci-thief/releases/download/v2.0.0/ci-thief_2.0.0_darwin_amd64.tar.gz"
      sha256 "8e10ec35320fda9eb3bcd878604c6a70974d63b34826c640ec9f330e7282a274"

      def install
        bin.install "ci-thief"

        # Install bash completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "bash")
        (bash_completion/"ci-thief").write output

        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "zsh")
        (zsh_completion/"_ci-thief").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/containeroo/ci-thief/releases/download/v2.0.0/ci-thief_2.0.0_linux_arm64.tar.gz"
      sha256 "ea43989b3fbdb5ee7551ee0aa0d0428cbc44b5fb58bd253f5a0d817eb5541e93"

      def install
        bin.install "ci-thief"

        # Install bash completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "bash")
        (bash_completion/"ci-thief").write output

        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "zsh")
        (zsh_completion/"_ci-thief").write output
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/containeroo/ci-thief/releases/download/v2.0.0/ci-thief_2.0.0_linux_armv6.tar.gz"
      sha256 "4e099c3fd6df1823ae97191a7664cc164545a2ccb6d99be9c065d927fb11a549"

      def install
        bin.install "ci-thief"

        # Install bash completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "bash")
        (bash_completion/"ci-thief").write output

        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "zsh")
        (zsh_completion/"_ci-thief").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/containeroo/ci-thief/releases/download/v2.0.0/ci-thief_2.0.0_linux_amd64.tar.gz"
      sha256 "fb613a8a23b36c60554f1bc78855c9981992ea6e5ff5acb2948c99fa1177fb64"

      def install
        bin.install "ci-thief"

        # Install bash completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "bash")
        (bash_completion/"ci-thief").write output

        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ci-thief", "completion", "zsh")
        (zsh_completion/"_ci-thief").write output
      end
    end
  end

  test do
    system "#{bin}/ci-thief version"
  end
end
