# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dologen < Formula
  desc "Simple CLI tool to generate Docker config.json with registry credentials"
  homepage "https://containeroo.ch"
  version "1.0.1"
  license "GNU General Public License v3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/containeroo/dologen/releases/download/v1.0.1/dologen_1.0.1_darwin_arm64.tar.gz"
      sha256 "1251a835cc6c9396291395e265d4d1f7f3755c679d13387cd07729be9b82cc75"

      def install
        bin.install "dologen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/containeroo/dologen/releases/download/v1.0.1/dologen_1.0.1_darwin_amd64.tar.gz"
      sha256 "84fa0b0aa31bb0b0fc7b0c585c107adeecbbfa72e508974c7ae7cfc51223cc53"

      def install
        bin.install "dologen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/containeroo/dologen/releases/download/v1.0.1/dologen_1.0.1_linux_amd64.tar.gz"
      sha256 "0033a42abcb1a7c35c30ef8d3b644a6da04715b4d0032baf8df8ffb223e5abfe"

      def install
        bin.install "dologen"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/containeroo/dologen/releases/download/v1.0.1/dologen_1.0.1_linux_armv6.tar.gz"
      sha256 "dbd4e53469ace1aab21db69acaf863506b0ffd9efdf61f8cc6a59a29e74e8145"

      def install
        bin.install "dologen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/containeroo/dologen/releases/download/v1.0.1/dologen_1.0.1_linux_arm64.tar.gz"
      sha256 "d169ff8b6d0cc535199706359ceb2db074fb031428ee11e3449709ca434198df"

      def install
        bin.install "dologen"
      end
    end
  end

  depends_on "go" => :optional

  test do
    system "#{bin}/dologen --version"
  end
end
