# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Syncflaer < Formula
  desc "Synchronize Traefik host rules and/or Kubernetes Ingresses with Cloudflare"
  homepage "https://containeroo.ch"
  version "5.4.1"
  license "GNU General Public License v3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/containeroo/SyncFlaer/releases/download/v5.4.1/SyncFlaer_5.4.1_darwin_arm64.tar.gz"
      sha256 "20bb57c5f30abf1887256a36692f5d88710a63cdfbf6e27f71aae984c5cdd71b"

      def install
        bin.install "syncflaer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/containeroo/SyncFlaer/releases/download/v5.4.1/SyncFlaer_5.4.1_darwin_amd64.tar.gz"
      sha256 "397fd451bb3e988a6b6bf0d6ea73a0205d36c2b2d571615b840c33953aadf80a"

      def install
        bin.install "syncflaer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/containeroo/SyncFlaer/releases/download/v5.4.1/SyncFlaer_5.4.1_linux_armv6.tar.gz"
      sha256 "18b96644c769b1775045f4679f96e4ca40baa2e2d3fc8f29c2ac0219de380a32"

      def install
        bin.install "syncflaer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/containeroo/SyncFlaer/releases/download/v5.4.1/SyncFlaer_5.4.1_linux_amd64.tar.gz"
      sha256 "512b9300e94bd6c46ea32d9076ed3a4fe29fef269645a507d6fc1701cf2548a3"

      def install
        bin.install "syncflaer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/containeroo/SyncFlaer/releases/download/v5.4.1/SyncFlaer_5.4.1_linux_arm64.tar.gz"
      sha256 "4cc9d370cff9ca40612ac28954882831a393ebbd16d17b1e85cd88a628934dde"

      def install
        bin.install "syncflaer"
      end
    end
  end

  depends_on "go" => :optional

  test do
    system "#{bin}/syncflaer --version"
  end
end
