# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Syncflaer < Formula
  desc "Synchronize Traefik host rules and/or Kubernetes Ingresses with Cloudflare"
  homepage "https://containeroo.ch"
  version "5.5.3"
  license "GNU General Public License v3.0"
  deprecate! date: "2026-02-16", because: :unmaintained

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/containeroo/SyncFlaer/releases/download/v5.5.3/SyncFlaer_5.5.3_darwin_amd64.tar.gz"
      sha256 "1865c0f9fb5a9e1069bfaa995f5583764f119893ce11dc91ddd3ae14fa561a86"

      def install
        bin.install "syncflaer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/containeroo/SyncFlaer/releases/download/v5.5.3/SyncFlaer_5.5.3_darwin_arm64.tar.gz"
      sha256 "b93af833e8e0341a35541460d6fe27f7c96cd4c047c2495ba5b6116061a57f52"

      def install
        bin.install "syncflaer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/containeroo/SyncFlaer/releases/download/v5.5.3/SyncFlaer_5.5.3_linux_arm64.tar.gz"
      sha256 "77572522dae1614c5595aa67dc11c5e4c35aaac70d95f16bdb92a12931bcd57b"

      def install
        bin.install "syncflaer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/containeroo/SyncFlaer/releases/download/v5.5.3/SyncFlaer_5.5.3_linux_amd64.tar.gz"
      sha256 "3c2bc0e234d95cb0ef083415c1f74e1fdb86ea9de85285ba08c6f91d1c492e8d"

      def install
        bin.install "syncflaer"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/containeroo/SyncFlaer/releases/download/v5.5.3/SyncFlaer_5.5.3_linux_armv6.tar.gz"
      sha256 "83619a49ed51dcd0f18a8e33580454f5b020d3e0ecee9132e53456b79cfd8c56"

      def install
        bin.install "syncflaer"
      end
    end
  end

  test do
    system "#{bin}/syncflaer --version"
  end
end
