# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SyncFlaer < Formula
  desc "Synchronize Traefik host rules and/or Kubernetes Ingresses with Cloudflare"
  homepage "https://containeroo.ch"
  version "5.4.1"
  license "GNU General Public License v3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/containeroo/SyncFlaer/releases/download/v5.4.1/SyncFlaer_5.4.1_darwin_arm64.tar.gz"
      sha256 "17a98b237459d6dae553485055628436062102642cd407205ba6c34558fe145f"

      def install
        bin.install "syncflaer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/containeroo/SyncFlaer/releases/download/v5.4.1/SyncFlaer_5.4.1_darwin_amd64.tar.gz"
      sha256 "6567f317b6bd7346c0c4993777f22e086ef2d65356f0ecf5d3d77910646324a3"

      def install
        bin.install "syncflaer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/containeroo/SyncFlaer/releases/download/v5.4.1/SyncFlaer_5.4.1_linux_arm64.tar.gz"
      sha256 "ce61966d448e547dc352a29dd3b66574ae9ffd281e6554175539a3e839d613a7"

      def install
        bin.install "syncflaer"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/containeroo/SyncFlaer/releases/download/v5.4.1/SyncFlaer_5.4.1_linux_armv6.tar.gz"
      sha256 "0c1c24385fccdf3e4d3c3b1a2fd0d3a0a2fcf67f98f4e2b8590c8e7189f13a03"

      def install
        bin.install "syncflaer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/containeroo/SyncFlaer/releases/download/v5.4.1/SyncFlaer_5.4.1_linux_amd64.tar.gz"
      sha256 "cba43522c38787ec8aa553b31672c178c106cfbcddc26cf8388464d5e203c779"

      def install
        bin.install "syncflaer"
      end
    end
  end

  depends_on "go" => :optional

  test do
    system "#{bin}/syncflaer --version"
  end
end
